trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - src/Api/*
      - ".azure/pipelines/api.yml"

pool:
  vmImageName: 'windows-latest'

variables:
  BuildConfiguration: Release
  workingDirectory: 'src/Api'


steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(workingDirectory)/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(workingDirectory)/*Tests/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Identity Provider'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(workingDirectory)/IdentityProvider/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build'
    zipAfterPublish: True

- task: DotNetCoreCLI@2
  displayName: 'Publish Submission API'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(workingDirectory)/SubmissionApi/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build'
    zipAfterPublish: True

- task: DotNetCoreCLI@2
  displayName: 'Publish Submission Job'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(workingDirectory)/SubmissionJob/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build'
    zipAfterPublish: True

- task: DotNetCoreCLI@2
  displayName: 'Publish Expiry Job'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(workingDirectory)/ExpiryJob/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
