# .NET Core Function App to Windows on Azure
# Build a .NET Core function app
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core 

trigger:
  batch: true
  branches:
    include:
    - "*"
  paths:
    include:
    - src/Analytics/*
    - ".azure/pipelines/build.analytics.yml"

pool:
  vmImage: windows-latest

variables:
  workingDirectory: "src/Analytics"

steps:
    # build web app (includes implicit nuget restore step)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
    command: 'build'
    projects: $(workingDirectory)/**/*.csproj
    arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    # archive and publish the web app to a deployable package
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: analytics_deploy_package
