# .NET Core Function App to Windows on Azure
# Build a .NET Core function app
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core 

trigger:
  batch: true
  branches:
    include:
    - main
pr: none

pool:
  vmImage: windows-latest

variables:
  workingDirectory: "src/Api/IdentityProvider"

steps:
  # Build Web App (Includes Implict Nuget Restore Step)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
        command: 'build'
        projects: $(workingDirectory)/**/*.csproj
        arguments: --configuration Release

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: $(workingDirectory)/**/*.csproj
      arguments: --output $(System.DefaultWorkingDirectory)/publish_output
      zipAfterPublish: false
      modifyOutputPath: false

  # Archive Built App
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/submissions_api_identity_webdeploy.zip
        replaceExistingArchive: true

  # Publish As Artifact
  - publish: $(Build.ArtifactStagingDirectory)/submissions_api_identity_webdeploy.zip
    artifact: submissions_api_identity_deploy_package
