trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - src/Data/*
      - ".azure/pipelines/build.data.yml"

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/Data/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Data/*.csproj'
    feedsToUse: 'select'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/Data'
    Contents: '**'
    TargetFolder: '$(Build.StagingDirectory)/Data'
    
- publish: '$(Build.StagingDirectory)/Data'
  artifact: data_migration