trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - src/Directory/*
      - ".azure/pipelines/build.directory.yml"

pool:
  vmImage: windows-latest

variables:
  solution: "src/Directory/*.sln"
  buildPlatform: Any CPU
  # buildConfiguration: 'Release'  ## Set In DevOps UI

jobs:
- job: BuildDirectory
  displayName: Build Directory
  steps:
    ## Nuget Restore
    - task: NuGetToolInstaller@1
      displayName: NuGet - Install Tools
      inputs:
        versionSpec: 5.x
    - task: NuGetCommand@2
      displayName: NuGet - Restore
      inputs:
        restoreSolution: $(solution)

    ## Publish Web App
    - task: VSBuild@1
      displayName: MSBuild - Publish
      inputs:
        solution: $(solution)
        msbuildArgs: >-
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:_PackageTempDir=C:/Package
          /p:PackageAsSingleFile=true
          /p:PrecompileBeforePublish=true
          /p:SkipInvalidConfigurations=true
          /p:PackageLocation="$(build.StagingDirectory)/webdeploy"
        platform: $(buildPlatform)
        configuration: $(buildConfiguration)

    - publish: $(build.StagingDirectory)/webdeploy
      artifact: webdeploy_package

    ## Publish ef6.exe And Identity Project For Migrations
    - task: CopyFiles@2
      displayName: Copy migration files
      inputs:
        SourceFolder: $(Build.SourcesDirectory)/src/Directory
        Contents: |
          packages/**/net45/win-x86/ef6.exe
          Identity/bin/**/*.dll
        TargetFolder: $(build.stagingdirectory)/db
        flattenFolders: true

    - publish: $(build.stagingdirectory)/db
      artifact: db_migration

## Build Data
- template: job.build.data.yml
