trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - src/Data/*
      - ".azure/pipelines/build.data.yml"

pool:
  vmImage: windows-latest

steps:
- template: job.build.data.yml