trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - src/Data/*
      - ".azure/pipelines/build.data.yml"

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'