trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/DataSeed.csproj'
    arguments: >-
      -c $(buildConfiguration)
      -o $(Build.StagingDirectory)
      --nologo
    workingDirectory: $(Build.SourcesDirectory)/Biobanks/DataSeed

- publish: $(Build.StagingDirectory)
  artifact: DataSeed
