# .NET Core Function App to Windows on Azure
# Build a .NET Core function app
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core 

trigger:
  batch: true
  branches:
    include:
    - main
pr:
  branches:
    include:
    - main
  paths:
    include:
    - "src/LegacyData/*"
    - "src/Api/Common/*"
    - "src/Api/SubmissionAzureFunction/*"
    - ".azure/pipelines/build.api.submissions.yml"

pool:
  vmImage: windows-latest

variables:
  workingDirectory: "src/Api/SubmissionAzureFunction"

steps:
    # Build Web App (includes implicit nuget restore step)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
        command: 'build'
        projects: $(workingDirectory)/**/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    # Archieve and Publish the web app to a deployable package
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/submissions_api_functions_webdeploy.zip
        replaceExistingArchive: true
  
  - publish: $(Build.ArtifactStagingDirectory)/submissions_api_functions_webdeploy.zip
    artifact: submissions_api_functions_deploy_package
