trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - src/Directory/DataSeed/*
      - src/Directory/Data/*
      - src/Directory/Entity/*
      - src/Directory/Services/*
      - ".azure/pipelines/build.dataseed.yml"

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release
  pwd: $(Build.SourcesDirectory)/src/Directory/DataSeed
  project: "**/DataSeed.csproj"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

steps:
  # we explicitly restore to ensure we use
  # the correct dotnet sdk version of nuget
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: $(project)
      arguments: --nologo
      workingDirectory: $(pwd)
  
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(project)
      arguments: >-
        -c $(buildConfiguration)
        -o $(Build.StagingDirectory)
        --no-restore
        --nologo
      workingDirectory: $(pwd)

  - publish: $(Build.StagingDirectory)
    artifact: DataSeed
