# deployments are never triggered by ci
# only by build completions
# or manually
trigger: none

# always trigger the deployment pipeline
# when a `master` build completes
resources:
  pipelines:
  - pipeline: build_web
    source: Biobanks (Legacy)/Directory (Build)
    trigger: 
      branches:
        include: 
        - master

# default to Cloud agents
# can override in individual stages/jobs
pool:
  vmImage: windows-latest

stages:
- stage: deploy_test_azure
  displayName: Deploy to Test (Azure)
  jobs:
  - deployment: deploy_test_azure
    displayName: Deploy to Test (Azure)
    environment: biobankinguk-directory-test

    variables:
    - group: ENV biobankinguk-directory-test

    strategy:
      runOnce:
        deploy:
          steps:
            # db migrations
          - task: SqlAzureDacpacDeployment@1
            displayName: Azure SQL Firewall rules
            inputs:
              azureSubscription: SV-ADAC-Biobanking-UK(72748e69-677a-4b7c-a2fb-97632e5e2d23)
              AuthenticationType: connectionString
              ConnectionString: $(dbConnectionString)
              deployType: InlineSqlTask
              SqlInline: select 1
              IpDetectionMethod: AutoDetect
              DeleteFirewallRule: false
          - script: >-
              ef6 database update
              -a Biobanks.Directory.Data.dll
              --connection-provider System.Data.SqlClient
              --connection-string "$(dbConnectionString)"
            displayName: Run Data migrations
            workingDirectory: $(Pipeline.Workspace)/build_web/db_migration
          - script: >-
              ef6 database update
              -a Biobanks.Directory.Identity.dll
              --connection-provider System.Data.SqlClient
              --connection-string "$(dbConnectionString)"
            displayName: Run Identity migrations
            workingDirectory: $(Pipeline.Workspace)/build_web/db_migration

          # deploy the web app
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: AzureRM
              azureSubscription: SV-ADAC-Biobanking-UK(72748e69-677a-4b7c-a2fb-97632e5e2d23)
              appType: webApp
              WebAppName: biobankinguk-directory-test
              packageForLinux: $(Pipeline.Workspace)/build_web/webdeploy_package/*.zip
