# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/Directory/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

pool:
  name: Default
  demands:
  - dotnet
  - npm

steps:
- script: dotnet build --nologo
  displayName: dotnet build Directory.csproj
  workingDirectory: src/Directory/Directory
- script: npm ci
  displayName: npm install (CI) for Theme
  workingDirectory: src/theme
- script: npm run build
  displayName: Build Shared Theme
  workingDirectory: src/theme
- script: npm ci
  displayName: npm install (CI) for Razor Pages
  workingDirectory: src/Directory/Directory
- script: npm run build
  displayName: Build Razor Pages bundles
  workingDirectory: src/Directory/Directory
- script: npm ci
  displayName: npm install (CI) for React
  workingDirectory: src/Directory/Directory/ClientApp
- script: npm run build
  displayName: Build React ClientApp
  workingDirectory: src/Directory/Directory/ClientApp