# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/Directory/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
- job: Dotnet
  pool:
    name: Default
    demands:
    - dotnet
  steps:
  - script: dotnet build -c Release --nologo
    displayName: Build Directory.csproj
    workingDirectory: src/Directory/Directory

- job: Frontend_ClientApp
  pool:
    name: Default
    demands:
    - npm
  variables:
    baseDir: src/Directory/Directory/ClientApp
  steps:
  - script: npm ci
    displayName: Install Dependencies
    workingDirectory: $(baseDir)
  - script: npm run build
    displayName: Build
    workingDirectory: $(baseDir)
  - upload: $(baseDir)/build
    artifact: clientapp
