# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/Directory/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

pool:
  name: Default
  demands:
  - dotnet
  - agent.os -equals Windows_NT # TODO: remove when all agents update to dotnet sdk 3.0

steps:
- script: dotnet build --nologo
  displayName: dotnet build Directory.csproj
  workingDirectory: src/Directory/Directory
  