# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - src/Upload/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

pool:
  name: Default
  demands:
  - dotnet

steps:
- script: dotnet build --nologo
  displayName: dotnet build Upload.csproj
  workingDirectory: src/Upload/Upload
  