// <auto-generated />
namespace Directory.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddAnalytics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAnalytics));
        
        string IMigrationMetadata.Id
        {
            get { return "202012021107205_AddAnalytics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
