// <auto-generated />
using System;
using Biobanks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Biobanks.Data.Migrations
{
    [DbContext(typeof(BiobanksDbContext))]
    [Migration("20210218162415_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnnotationPublication", b =>
                {
                    b.Property<int>("AnnotationsId")
                        .HasColumnType("int");

                    b.Property<int>("PublicationsId")
                        .HasColumnType("int");

                    b.HasKey("AnnotationsId", "PublicationsId");

                    b.HasIndex("PublicationsId");

                    b.ToTable("AnnotationPublication");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordIdentifiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.LiveDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateDiagnosed")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisCodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiagnosisCodeOntologyVersionId")
                        .HasColumnType("int");

                    b.Property<string>("IndividualReferenceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmissionTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisCodeId");

                    b.HasIndex("DiagnosisCodeOntologyVersionId");

                    b.HasIndex("OrganisationId", "IndividualReferenceId", "DateDiagnosed", "DiagnosisCodeId")
                        .IsUnique();

                    b.ToTable("LiveDiagnoses");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.LiveSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AgeAtDonation")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollectionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("ExtractionProcedureId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExtractionSiteId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ExtractionSiteOntologyVersionId")
                        .HasColumnType("int");

                    b.Property<string>("IndividualReferenceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("PreservationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SampleContentId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SampleContentMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("SexId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageTemperatureId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmissionTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionProcedureId");

                    b.HasIndex("ExtractionSiteId");

                    b.HasIndex("ExtractionSiteOntologyVersionId");

                    b.HasIndex("MaterialTypeId");

                    b.HasIndex("PreservationTypeId");

                    b.HasIndex("SampleContentId");

                    b.HasIndex("SampleContentMethodId");

                    b.HasIndex("SexId");

                    b.HasIndex("StorageTemperatureId");

                    b.HasIndex("OrganisationId", "IndividualReferenceId", "Barcode", "CollectionName")
                        .IsUnique()
                        .HasFilter("[CollectionName] IS NOT NULL");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.LiveTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndividualReferenceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmissionTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TreatmentCodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TreatmentCodeOntologyVersionId")
                        .HasColumnType("int");

                    b.Property<int?>("TreatmentLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentCodeId");

                    b.HasIndex("TreatmentCodeOntologyVersionId");

                    b.HasIndex("TreatmentLocationId");

                    b.HasIndex("OrganisationId", "IndividualReferenceId", "DateTreated", "TreatmentCodeId")
                        .IsUnique();

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.ReferenceData.Ontology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ontologies");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.ReferenceData.OntologyVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("OntologyId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OntologyId");

                    b.ToTable("OntologyVersions");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.ReferenceData.SampleContentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SampleContentMethods");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.ReferenceData.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.ReferenceData.TreatmentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TreatmentLocations");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateDiagnosed")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisCodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiagnosisCodeOntologyVersionId")
                        .HasColumnType("int");

                    b.Property<string>("IndividualReferenceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmissionTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisCodeId");

                    b.HasIndex("DiagnosisCodeOntologyVersionId");

                    b.HasIndex("OrganisationId", "IndividualReferenceId", "DateDiagnosed", "DiagnosisCodeId")
                        .IsUnique();

                    b.ToTable("StagedDiagnoses");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedDiagnosisDelete", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StagedDiagnosisDeletes");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AgeAtDonation")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollectionName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("ExtractionProcedureId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExtractionSiteId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ExtractionSiteOntologyVersionId")
                        .HasColumnType("int");

                    b.Property<string>("IndividualReferenceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("PreservationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SampleContentId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SampleContentMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("SexId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageTemperatureId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmissionTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionProcedureId");

                    b.HasIndex("ExtractionSiteId");

                    b.HasIndex("ExtractionSiteOntologyVersionId");

                    b.HasIndex("MaterialTypeId");

                    b.HasIndex("PreservationTypeId");

                    b.HasIndex("SampleContentId");

                    b.HasIndex("SampleContentMethodId");

                    b.HasIndex("SexId");

                    b.HasIndex("StorageTemperatureId");

                    b.HasIndex("OrganisationId", "IndividualReferenceId", "Barcode", "CollectionName")
                        .IsUnique()
                        .HasFilter("[CollectionName] IS NOT NULL");

                    b.ToTable("StagedSamples");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedSampleDelete", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StagedSampleDeletes");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndividualReferenceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmissionTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TreatmentCodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TreatmentCodeOntologyVersionId")
                        .HasColumnType("int");

                    b.Property<int?>("TreatmentLocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentCodeId");

                    b.HasIndex("TreatmentCodeOntologyVersionId");

                    b.HasIndex("TreatmentLocationId");

                    b.HasIndex("OrganisationId", "IndividualReferenceId", "DateTreated", "TreatmentCodeId")
                        .IsUnique();

                    b.ToTable("StagedTreatments");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedTreatmentDelete", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StagedTreatmentDeletes");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BiobankId")
                        .HasColumnType("int");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusChangeTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Blob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentDisposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.CapabilityAssociatedData", b =>
                {
                    b.Property<int>("DiagnosisCapabilityId")
                        .HasColumnType("int");

                    b.Property<int>("AssociatedDataTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssociatedDataProcurementTimeframeId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisCapabilityId", "AssociatedDataTypeId");

                    b.HasIndex("AssociatedDataProcurementTimeframeId");

                    b.HasIndex("AssociatedDataTypeId");

                    b.ToTable("CapabilityAssociatedDatas");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccessConditionId")
                        .HasColumnType("int");

                    b.Property<int>("CollectionPointId")
                        .HasColumnType("int");

                    b.Property<int>("CollectionStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FromApi")
                        .HasColumnType("bit");

                    b.Property<int?>("HtaStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("OntologyTermId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CollectionId");

                    b.HasIndex("AccessConditionId");

                    b.HasIndex("CollectionPointId");

                    b.HasIndex("CollectionStatusId");

                    b.HasIndex("CollectionTypeId");

                    b.HasIndex("HtaStatusId");

                    b.HasIndex("OntologyTermId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.CollectionAssociatedData", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<int>("AssociatedDataTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssociatedDataProcurementTimeframeId")
                        .HasColumnType("int");

                    b.HasKey("CollectionId", "AssociatedDataTypeId");

                    b.HasIndex("AssociatedDataProcurementTimeframeId");

                    b.HasIndex("AssociatedDataTypeId");

                    b.ToTable("CollectionAssociatedDatas");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.CollectionSampleSet", b =>
                {
                    b.Property<int>("SampleSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AgeRangeId")
                        .HasColumnType("int");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<int>("DonorCountId")
                        .HasColumnType("int");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.HasKey("SampleSetId");

                    b.HasIndex("AgeRangeId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("DonorCountId");

                    b.HasIndex("SexId");

                    b.ToTable("CollectionSampleSets");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Config", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.DiagnosisCapability", b =>
                {
                    b.Property<int>("DiagnosisCapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnnualDonorExpectation")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("OntologyTermId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("SampleCollectionModeId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisCapabilityId");

                    b.HasIndex("OntologyTermId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("SampleCollectionModeId");

                    b.ToTable("DiagnosisCapabilities");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.MaterialDetail", b =>
                {
                    b.Property<int>("SampleSetId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StorageTemperatureId")
                        .HasColumnType("int");

                    b.Property<int>("MacroscopicAssessmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectionPercentageId")
                        .HasColumnType("int");

                    b.Property<int?>("PreservationTypeId")
                        .HasColumnType("int");

                    b.HasKey("SampleSetId", "MaterialTypeId", "StorageTemperatureId", "MacroscopicAssessmentId");

                    b.HasIndex("CollectionPercentageId");

                    b.HasIndex("MacroscopicAssessmentId");

                    b.HasIndex("MaterialTypeId");

                    b.HasIndex("PreservationTypeId");

                    b.HasIndex("StorageTemperatureId");

                    b.ToTable("MaterialDetails");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Network", b =>
                {
                    b.Property<int>("NetworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("ContactHandoverEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandoverBaseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HandoverNonMembers")
                        .HasColumnType("bit");

                    b.Property<string>("HandoverNonMembersUrlParamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandoverOrgIdsUrlParamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MultipleHandoverOrdIdsParams")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SopStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NetworkId");

                    b.HasIndex("SopStatusId");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.NetworkRegisterRequest", b =>
                {
                    b.Property<int>("NetworkRegisterRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeclinedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NetworkCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NetworkRegisterRequestId");

                    b.ToTable("NetworkRegisterRequests");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.NetworkUser", b =>
                {
                    b.Property<int>("NetworkId")
                        .HasColumnType("int");

                    b.Property<string>("NetworkUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NetworkId", "NetworkUserId");

                    b.ToTable("NetworkUsers");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Organisation", b =>
                {
                    b.Property<int>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AnonymousIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EthicsRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExcludePublications")
                        .HasColumnType("bit");

                    b.Property<string>("GoverningDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoverningInstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtaLicence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganisationExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("OtherRegistrationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SharingOptOut")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganisationId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CountyId");

                    b.HasIndex("OrganisationTypeId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationAnnualStatistic", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("AnnualStatisticId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("OrganisationId", "AnnualStatisticId", "Year");

                    b.HasIndex("AnnualStatisticId");

                    b.ToTable("OrganisationAnnualStatistics");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationNetwork", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("NetworkId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganisationId", "NetworkId");

                    b.HasIndex("NetworkId");

                    b.ToTable("OrganisationNetworks");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationRegisterRequest", b =>
                {
                    b.Property<int>("OrganisationRegisterRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeclinedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrganisationCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganisationExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganisationRegisterRequestId");

                    b.HasIndex("OrganisationTypeId");

                    b.ToTable("OrganisationRegisterRequests");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationRegistrationReason", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationReasonId")
                        .HasColumnType("int");

                    b.HasKey("OrganisationId", "RegistrationReasonId");

                    b.HasIndex("RegistrationReasonId");

                    b.ToTable("OrganisationRegistrationReasons");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationServiceOffering", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOfferingId")
                        .HasColumnType("int");

                    b.HasKey("OrganisationId", "ServiceOfferingId");

                    b.HasIndex("ServiceOfferingId");

                    b.ToTable("OrgServiceOfferings");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationType", b =>
                {
                    b.Property<int>("OrganisationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("OrganisationTypeId");

                    b.ToTable("OrganisationTypes");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationUser", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("OrganisationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrganisationId", "OrganisationUserId");

                    b.ToTable("OrganisationUsers");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool?>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AnnotationsSynced")
                        .HasColumnType("datetime2");

                    b.Property<string>("Authors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Journal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("PublicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AccessCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessConditions");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AgeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgeRanges");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AnnualStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnnualStatisticGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnnualStatisticGroupId");

                    b.ToTable("AnnualStatistics");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AnnualStatisticGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnnualStatisticGroups");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AssociatedDataProcurementTimeframe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssociatedDataProcurementTimeframes");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AssociatedDataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AssociatedDataTypeGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedDataTypeGroupId");

                    b.ToTable("AssociatedDataTypes");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AssociatedDataTypeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssociatedDataTypeGroups");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.CollectionPercentage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("UpperBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectionPercentages");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.CollectionPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectionPoints");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.CollectionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectionStatus");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.CollectionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectionTypes");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.ConsentRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConsentRestrictions");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Counties");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.DonorCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("LowerBound")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("UpperBound")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonorCounts");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.Funder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funders");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.HtaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HtaStatus");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.MacroscopicAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MacroscopicAssessments");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.RegistrationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationReasons");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.SampleCollectionMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SampleCollectionModes");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.ServiceOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceOfferings");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.SopStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SopStatus");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.TokenIssueRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TokenIssueRecords");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.TokenValidationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ValidationSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TokenValidationRecords");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.MaterialTypeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypeGroups");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OtherTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SnomedTagId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SnomedTagId");

                    b.ToTable("OntologyTerms");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.PreservationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("StorageTemperatureId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StorageTemperatureId");

                    b.ToTable("PreservationTypes");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sexes");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.SnomedTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SnomedTags");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.StorageTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StorageTemperatures");
                });

            modelBuilder.Entity("CollectionConsentRestriction", b =>
                {
                    b.Property<int>("CollectionsCollectionId")
                        .HasColumnType("int");

                    b.Property<int>("ConsentRestrictionsId")
                        .HasColumnType("int");

                    b.HasKey("CollectionsCollectionId", "ConsentRestrictionsId");

                    b.HasIndex("ConsentRestrictionsId");

                    b.ToTable("CollectionConsentRestriction");
                });

            modelBuilder.Entity("FunderOrganisation", b =>
                {
                    b.Property<int>("FundersId")
                        .HasColumnType("int");

                    b.Property<int>("OrganisationsOrganisationId")
                        .HasColumnType("int");

                    b.HasKey("FundersId", "OrganisationsOrganisationId");

                    b.HasIndex("OrganisationsOrganisationId");

                    b.ToTable("FunderOrganisation");
                });

            modelBuilder.Entity("MaterialTypeMaterialTypeGroup", b =>
                {
                    b.Property<int>("MaterialTypeGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialTypesId")
                        .HasColumnType("int");

                    b.HasKey("MaterialTypeGroupsId", "MaterialTypesId");

                    b.HasIndex("MaterialTypesId");

                    b.ToTable("MaterialTypeMaterialTypeGroup");
                });

            modelBuilder.Entity("AnnotationPublication", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.Annotation", null)
                        .WithMany()
                        .HasForeignKey("AnnotationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.Publication", null)
                        .WithMany()
                        .HasForeignKey("PublicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biobanks.Entities.Api.Error", b =>
                {
                    b.HasOne("Biobanks.Entities.Api.Submission", "Submission")
                        .WithMany("Errors")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.LiveDiagnosis", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "DiagnosisCode")
                        .WithMany()
                        .HasForeignKey("DiagnosisCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.OntologyVersion", "DiagnosisCodeOntologyVersion")
                        .WithMany()
                        .HasForeignKey("DiagnosisCodeOntologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiagnosisCode");

                    b.Navigation("DiagnosisCodeOntologyVersion");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.LiveSample", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "ExtractionProcedure")
                        .WithMany()
                        .HasForeignKey("ExtractionProcedureId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "ExtractionSite")
                        .WithMany()
                        .HasForeignKey("ExtractionSiteId");

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.OntologyVersion", "ExtractionSiteOntologyVersion")
                        .WithMany()
                        .HasForeignKey("ExtractionSiteOntologyVersionId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.PreservationType", "PreservationType")
                        .WithMany()
                        .HasForeignKey("PreservationTypeId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "SampleContent")
                        .WithMany()
                        .HasForeignKey("SampleContentId");

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.SampleContentMethod", "SampleContentMethod")
                        .WithMany()
                        .HasForeignKey("SampleContentMethodId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.StorageTemperature", "StorageTemperature")
                        .WithMany()
                        .HasForeignKey("StorageTemperatureId");

                    b.Navigation("ExtractionProcedure");

                    b.Navigation("ExtractionSite");

                    b.Navigation("ExtractionSiteOntologyVersion");

                    b.Navigation("MaterialType");

                    b.Navigation("PreservationType");

                    b.Navigation("SampleContent");

                    b.Navigation("SampleContentMethod");

                    b.Navigation("Sex");

                    b.Navigation("StorageTemperature");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.LiveTreatment", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "TreatmentCode")
                        .WithMany()
                        .HasForeignKey("TreatmentCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.OntologyVersion", "TreatmentCodeOntologyVersion")
                        .WithMany()
                        .HasForeignKey("TreatmentCodeOntologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.TreatmentLocation", "TreatmentLocation")
                        .WithMany()
                        .HasForeignKey("TreatmentLocationId");

                    b.Navigation("TreatmentCode");

                    b.Navigation("TreatmentCodeOntologyVersion");

                    b.Navigation("TreatmentLocation");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.ReferenceData.OntologyVersion", b =>
                {
                    b.HasOne("Biobanks.Entities.Api.ReferenceData.Ontology", "Ontology")
                        .WithMany("OntologyVersions")
                        .HasForeignKey("OntologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ontology");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedDiagnosis", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "DiagnosisCode")
                        .WithMany()
                        .HasForeignKey("DiagnosisCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.OntologyVersion", "DiagnosisCodeOntologyVersion")
                        .WithMany()
                        .HasForeignKey("DiagnosisCodeOntologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiagnosisCode");

                    b.Navigation("DiagnosisCodeOntologyVersion");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedSample", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "ExtractionProcedure")
                        .WithMany()
                        .HasForeignKey("ExtractionProcedureId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "ExtractionSite")
                        .WithMany()
                        .HasForeignKey("ExtractionSiteId");

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.OntologyVersion", "ExtractionSiteOntologyVersion")
                        .WithMany()
                        .HasForeignKey("ExtractionSiteOntologyVersionId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.PreservationType", "PreservationType")
                        .WithMany()
                        .HasForeignKey("PreservationTypeId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "SampleContent")
                        .WithMany()
                        .HasForeignKey("SampleContentId");

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.SampleContentMethod", "SampleContentMethod")
                        .WithMany()
                        .HasForeignKey("SampleContentMethodId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.StorageTemperature", "StorageTemperature")
                        .WithMany()
                        .HasForeignKey("StorageTemperatureId");

                    b.Navigation("ExtractionProcedure");

                    b.Navigation("ExtractionSite");

                    b.Navigation("ExtractionSiteOntologyVersion");

                    b.Navigation("MaterialType");

                    b.Navigation("PreservationType");

                    b.Navigation("SampleContent");

                    b.Navigation("SampleContentMethod");

                    b.Navigation("Sex");

                    b.Navigation("StorageTemperature");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.StagedTreatment", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "TreatmentCode")
                        .WithMany()
                        .HasForeignKey("TreatmentCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.OntologyVersion", "TreatmentCodeOntologyVersion")
                        .WithMany()
                        .HasForeignKey("TreatmentCodeOntologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Api.ReferenceData.TreatmentLocation", "TreatmentLocation")
                        .WithMany()
                        .HasForeignKey("TreatmentLocationId");

                    b.Navigation("TreatmentCode");

                    b.Navigation("TreatmentCodeOntologyVersion");

                    b.Navigation("TreatmentLocation");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.Submission", b =>
                {
                    b.HasOne("Biobanks.Entities.Api.ReferenceData.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.CapabilityAssociatedData", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AssociatedDataProcurementTimeframe", "AssociatedDataProcurementTimeframe")
                        .WithMany()
                        .HasForeignKey("AssociatedDataProcurementTimeframeId");

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AssociatedDataType", "AssociatedDataType")
                        .WithMany()
                        .HasForeignKey("AssociatedDataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.DiagnosisCapability", "DiagnosisCapability")
                        .WithMany("AssociatedData")
                        .HasForeignKey("DiagnosisCapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedDataProcurementTimeframe");

                    b.Navigation("AssociatedDataType");

                    b.Navigation("DiagnosisCapability");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Collection", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AccessCondition", "AccessCondition")
                        .WithMany()
                        .HasForeignKey("AccessConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.CollectionPoint", "CollectionPoint")
                        .WithMany()
                        .HasForeignKey("CollectionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.CollectionStatus", "CollectionStatus")
                        .WithMany()
                        .HasForeignKey("CollectionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.CollectionType", "CollectionType")
                        .WithMany()
                        .HasForeignKey("CollectionTypeId");

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.HtaStatus", "HtaStatus")
                        .WithMany()
                        .HasForeignKey("HtaStatusId");

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "OntologyTerm")
                        .WithMany()
                        .HasForeignKey("OntologyTermId");

                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany("Collections")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessCondition");

                    b.Navigation("CollectionPoint");

                    b.Navigation("CollectionStatus");

                    b.Navigation("CollectionType");

                    b.Navigation("HtaStatus");

                    b.Navigation("OntologyTerm");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.CollectionAssociatedData", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AssociatedDataProcurementTimeframe", "AssociatedDataProcurementTimeframe")
                        .WithMany()
                        .HasForeignKey("AssociatedDataProcurementTimeframeId");

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AssociatedDataType", "AssociatedDataType")
                        .WithMany()
                        .HasForeignKey("AssociatedDataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.Collection", "Collection")
                        .WithMany("AssociatedData")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedDataProcurementTimeframe");

                    b.Navigation("AssociatedDataType");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.CollectionSampleSet", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AgeRange", "AgeRange")
                        .WithMany()
                        .HasForeignKey("AgeRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.Collection", "Collection")
                        .WithMany("SampleSets")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.DonorCount", "DonorCount")
                        .WithMany()
                        .HasForeignKey("DonorCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeRange");

                    b.Navigation("Collection");

                    b.Navigation("DonorCount");

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.DiagnosisCapability", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", "OntologyTerm")
                        .WithMany()
                        .HasForeignKey("OntologyTermId");

                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany("DiagnosisCapabilities")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.SampleCollectionMode", "SampleCollectionMode")
                        .WithMany()
                        .HasForeignKey("SampleCollectionModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OntologyTerm");

                    b.Navigation("Organisation");

                    b.Navigation("SampleCollectionMode");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.MaterialDetail", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.CollectionPercentage", "CollectionPercentage")
                        .WithMany()
                        .HasForeignKey("CollectionPercentageId");

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.MacroscopicAssessment", "MacroscopicAssessment")
                        .WithMany()
                        .HasForeignKey("MacroscopicAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.PreservationType", "PreservationType")
                        .WithMany()
                        .HasForeignKey("PreservationTypeId");

                    b.HasOne("Biobanks.Entities.Data.CollectionSampleSet", null)
                        .WithMany("MaterialDetails")
                        .HasForeignKey("SampleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.StorageTemperature", "StorageTemperature")
                        .WithMany()
                        .HasForeignKey("StorageTemperatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionPercentage");

                    b.Navigation("MacroscopicAssessment");

                    b.Navigation("MaterialType");

                    b.Navigation("PreservationType");

                    b.Navigation("StorageTemperature");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Network", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.SopStatus", "SopStatus")
                        .WithMany()
                        .HasForeignKey("SopStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SopStatus");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.NetworkUser", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.Network", "Network")
                        .WithMany()
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Organisation", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.Country", "Country")
                        .WithMany("Organisations")
                        .HasForeignKey("CountryId");

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.County", "County")
                        .WithMany("Organisations")
                        .HasForeignKey("CountyId");

                    b.HasOne("Biobanks.Entities.Data.OrganisationType", "OrganisationType")
                        .WithMany()
                        .HasForeignKey("OrganisationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("County");

                    b.Navigation("OrganisationType");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationAnnualStatistic", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AnnualStatistic", "AnnualStatistic")
                        .WithMany("OrganisationAnnualStatistics")
                        .HasForeignKey("AnnualStatisticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany("OrganisationAnnualStatistics")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnualStatistic");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationNetwork", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.Network", "Network")
                        .WithMany("OrganisationNetworks")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany("OrganisationNetworks")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationRegisterRequest", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.OrganisationType", "OrganisationType")
                        .WithMany()
                        .HasForeignKey("OrganisationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganisationType");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationRegistrationReason", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany("OrganisationRegistrationReasons")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.RegistrationReason", "RegistrationReason")
                        .WithMany()
                        .HasForeignKey("RegistrationReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("RegistrationReason");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationServiceOffering", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany("OrganisationServiceOfferings")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.ServiceOffering", "ServiceOffering")
                        .WithMany("OrganisationServiceOfferings")
                        .HasForeignKey("ServiceOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("ServiceOffering");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.OrganisationUser", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany("OrganisationUsers")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Publication", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AnnualStatistic", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AnnualStatisticGroup", "AnnualStatisticGroup")
                        .WithMany("AnnualStatistics")
                        .HasForeignKey("AnnualStatisticGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnualStatisticGroup");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AssociatedDataType", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.AssociatedDataTypeGroup", "AssociatedDataTypeGroup")
                        .WithMany("AssociatedDataTypes")
                        .HasForeignKey("AssociatedDataTypeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedDataTypeGroup");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.County", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.Country", "Country")
                        .WithMany("Counties")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.OntologyTerm", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.SnomedTag", "SnomedTag")
                        .WithMany("OntologyTerms")
                        .HasForeignKey("SnomedTagId");

                    b.Navigation("SnomedTag");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.PreservationType", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.StorageTemperature", "StorageTemperature")
                        .WithMany()
                        .HasForeignKey("StorageTemperatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageTemperature");
                });

            modelBuilder.Entity("CollectionConsentRestriction", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.ReferenceData.ConsentRestriction", null)
                        .WithMany()
                        .HasForeignKey("ConsentRestrictionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FunderOrganisation", b =>
                {
                    b.HasOne("Biobanks.Entities.Data.ReferenceData.Funder", null)
                        .WithMany()
                        .HasForeignKey("FundersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Data.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationsOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialTypeMaterialTypeGroup", b =>
                {
                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.MaterialTypeGroup", null)
                        .WithMany()
                        .HasForeignKey("MaterialTypeGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biobanks.Entities.Shared.ReferenceData.MaterialType", null)
                        .WithMany()
                        .HasForeignKey("MaterialTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biobanks.Entities.Api.ReferenceData.Ontology", b =>
                {
                    b.Navigation("OntologyVersions");
                });

            modelBuilder.Entity("Biobanks.Entities.Api.Submission", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Collection", b =>
                {
                    b.Navigation("AssociatedData");

                    b.Navigation("SampleSets");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.CollectionSampleSet", b =>
                {
                    b.Navigation("MaterialDetails");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.DiagnosisCapability", b =>
                {
                    b.Navigation("AssociatedData");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Network", b =>
                {
                    b.Navigation("OrganisationNetworks");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.Organisation", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("DiagnosisCapabilities");

                    b.Navigation("OrganisationAnnualStatistics");

                    b.Navigation("OrganisationNetworks");

                    b.Navigation("OrganisationRegistrationReasons");

                    b.Navigation("OrganisationServiceOfferings");

                    b.Navigation("OrganisationUsers");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AnnualStatistic", b =>
                {
                    b.Navigation("OrganisationAnnualStatistics");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AnnualStatisticGroup", b =>
                {
                    b.Navigation("AnnualStatistics");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.AssociatedDataTypeGroup", b =>
                {
                    b.Navigation("AssociatedDataTypes");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.Country", b =>
                {
                    b.Navigation("Counties");

                    b.Navigation("Organisations");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.County", b =>
                {
                    b.Navigation("Organisations");
                });

            modelBuilder.Entity("Biobanks.Entities.Data.ReferenceData.ServiceOffering", b =>
                {
                    b.Navigation("OrganisationServiceOfferings");
                });

            modelBuilder.Entity("Biobanks.Entities.Shared.ReferenceData.SnomedTag", b =>
                {
                    b.Navigation("OntologyTerms");
                });
#pragma warning restore 612, 618
        }
    }
}
