# Manual trigger only
trigger: none

# Trigger after building 'master'
resources:
  pipelines:
  - pipeline: build_web
    source: Biobanks (Legacy)/Directory (Build)
    trigger: 
      branches:
        include: 
        - master

pool:
  vmImage: windows-latest

variables:
  environment: 'who-directory-test'
  ## Azure Resources
  azureSubscription: 'SV-ADAC-Biobanking-UK(72748e69-677a-4b7c-a2fb-97632e5e2d23)'
  resourceGroupName: 'who-directory-test'
  webAppName: 'finddx-directory-test'
  keyVaultName: 'who-directory-test'

stages:
- stage: DeployTestAzure
  displayName: Deploy to Test (Azure)
  jobs:
  - deployment: DeployTestAzure
    displayName: Deploy to Test (Azure)
    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:
          ## Fetch Database Credentials / Connection String
          - task: AzureKeyVault@1
            displayName:  'Fetch Database Credentials'
            inputs:
              azureSubscription: '$(azureSubscription)'
              keyVaultName: '$(keyVaultName)'
              secretsFilter: '*'
              runAsPreJob: false

          - powershell: |
              $dbConnection = "$(sqldb-connection)" -f "$(sqldb-username)", "$(sqldb-password)"
              Write-Host "##vso[task.setvariable variable=dbConnectionString;]$dbConnection"
            displayName: Parse Database Connection String

          ## Migrate Database
          - task: SqlAzureDacpacDeployment@1
            displayName: Azure SQL Firewall rules
            inputs:
              azureSubscription: $(azureSubscription)
              AuthenticationType: connectionString
              ConnectionString: $(dbConnectionString)
              deployType: InlineSqlTask
              SqlInline: select 1
              IpDetectionMethod: AutoDetect
              DeleteFirewallRule: false
          - script: >-
              ef6 database update
              -a Biobanks.Directory.Data.dll
              --connection-provider System.Data.SqlClient
              --connection-string "$(dbConnectionString)"
            displayName: Run Data Migrations
            workingDirectory: $(Pipeline.Workspace)/build_web/db_migration
          - script: >-
              ef6 database update
              -a Biobanks.Directory.Identity.dll
              --connection-provider System.Data.SqlClient
              --connection-string "$(dbConnectionString)"
            displayName: Run Identity Migrations
            workingDirectory: $(Pipeline.Workspace)/build_web/db_migration
          
          # Deploy Web App
          - task: AzureRmWebAppDeployment@4
            displayName: Deploy Web App
            inputs:
              ConnectionType: AzureRM
              azureSubscription: $(azureSubscription)
              appType: webApp
              WebAppName: $(webAppName)
              packageForLinux: $(Pipeline.Workspace)/build_web/webdeploy_package/*.zip

          - task: AzureAppServiceSettings@1
            displayName: Update App Configuration
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: $(webAppName)  
              resourceGroupName: $(resourceGroupName)
              connectionStrings: |
                [
                  {
                    "name": "Biobanks",
                    "value": "$(dbConnectionString)",
                    "type": "SQLServer",
                    "slotSetting": false
                  },
                  {
                    "name": "elmah",
                    "value": "$(dbConnectionString)",
                    "type": "SQLServer",
                    "slotSetting": false
                  }
                ]
