# This docker compose will stand up a local instance of elasticsearch 8.x for development use
# This saves manually installing java, elastic, and kibana.
# we expose the default elastic ports 9200 and 9300; you can change them below if those ports are in use
# use Postman to hit the server on 9200, or stand up a kibana container if you really need to.

services:
  elastic-search:
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
