root: true
env:
  browser: true
extends:
  - eslint:recommended
globals:
  # vendor globals
  $: readonly
  jQuery: readonly
  bootbox: readonly
  ko: readonly

  # source globals
  logoBaseUrl: readonly
parserOptions:
  ecmaVersion: 5
  sourceType: script
