name: Build docs

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/build.docs.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16
          run_install: true
      - name: docs - pnpm build
        run: >-
          pnpm -C docs build
