name: Build Directory

on:
  workflow_dispatch:
  pull_request:
    paths:
      - lib/Core/**
      - lib/Data/**
      - app/Directory/**
      - .github/workflows/build.directory.yml

env:
  # Configure these
  build-config: release
  dotnet-version: 8.0.x
  project: ./app/Directory/Directory.csproj
  frontend-package: frontend

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # pnpm install so we have frontend dependencies for bundling
      - uses: ./.github/actions/template.pnpm-install
        with:
          filter: ${{ env.frontend-package }}

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: dotnet build
        run: >-
          dotnet build
          ${{ env.project }}
          -c ${{ env.build-config }}
