name: Build docs

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/build.docs.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/template.pnpm-install
        with:
          node-version: "16"
          filter: docs

      - name: docs - pnpm build
        run: |
          pnpm i --filter docs
          pnpm --filter docs build
