name: Build Core

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - src/Core/**

env:
  # Configure these
  CI_build-config: release
  CI_dotnet-version: 5.0.x
  CI_project: ./src/Core/Core.csproj

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.CI_dotnet-version }}
      - name: dotnet build
        run: >-
          dotnet build
          ${{ env.CI_project }}
          -c ${{ env.CI_build-config }}