name: Build DataSeed

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - src/DataSeed/**
      - src/Data/**
      - src/Entities/**
      - src/Directory/Services/**
      - .github/workflows/build.dataseed.yml

jobs:
  build:

    env:
      BUILD_CONFIG: release
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    defaults:
      run:
        working-directory: src/DataSeed

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: >-
        dotnet restore
    
    - name: Publish App
      run: >-
        dotnet publish
        --no-restore
        -c ${{ env.BUILD_CONFIG }}
        -o ${{ env.GITHUB_WORKSPACE }}/.publish
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dataseed
        path: ./.publish