name: GitHub Pages Docs

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/publish.docs.yml

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.16
          run_install: true

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_SSH }}

      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          pnpm i --filter docs
          pnpm -C docs deploy
