# This workflow is currently manually triggered
# TODO: In future we will also trigger it by successful completion\
# of suitable branches (e.g. `main`, `support/`)
# so that they deploy "nightly" style releases to a reusable tag

# It takes a workflow run id (expected to be a `publish.directory` run)
# downloads the published artifacts
# creates a release using the app version of the commit
# the artifacts were published from
name: GitHub Release
on:
  workflow_dispatch:
    inputs:
      publish-run-id:
        description: The Workflow Run ID for a successful Publish of the Directory
        required: true
        type: string
      override-tag:
        description: The tag to release against (optional; defaults to a version tag)
        required: false
        type: string
        default: ""
      is-latest:
        description: Should this release be marked as "latest"?
        required: false
        default: false
        type: boolean

env:
  valid-workflow-id: 53174516 # publish.directory
  run-id: ${{ github.event.inputs.publish-run-id }}
  is-latest: ${{ github.event.inputs.is-latest }}

jobs:
  # get some info on the workflow run so we can
  # - validate it
  # - check out its source for info
  fetch-run:
    runs-on: ubuntu-latest
    outputs:
      publish-commit: ${{ fromJSON(steps.run-info.outputs.result).head_sha }}
    steps:
      - name: Get workflow run
        id: run-info
        uses: actions/github-script@v7
        with:
          script: |
            const { data: { workflow_id, head_sha, conclusion } } =
              await github.rest.actions.getWorkflowRun({
                owner: 'biobankinguk',
                repo: 'biobankinguk',
                run_id: ${{ env.run-id }}
              });
            return { workflow_id, head_sha, conclusion };

      # Fail this run if anything about the target run is invalid
      - name: Fail invalid workflow run
        if: |
          fromJSON(steps.run-info.outputs.result).workflow_id != env.valid-workflow-id || 
          fromJSON(steps.run-info.outputs.result).conclusion != 'success'
        run: exit 1

  release:
    runs-on: ubuntu-latest
    needs: [fetch-run]
    steps:
      # determine version from the workflow run's commit
      - name: Checkout target workflow run's commit
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.fetch-run.outputs.publish-commit }}
      - name: Read version
        id: version
        uses: bbonkr/get-version-action@v1
        with:
          project: app/Directory/Directory.csproj

      # download artifacts from the run we want on the release
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ env.run-id }}
          skip_unpack: true # leave them zipped

      # Conditionally prep some variables for the Release
      - name: set Release Tag to Version
        if: ${{ github.event.inputs.override-tag == '' }}
        run: |
          echo "RELEASE_TAG=v${{ steps.version.outputs.version }}" >> $GITHUB_ENV
      - name: set Release Tag to Override Value
        if: ${{ github.event.inputs.override-tag != '' }}
        run: |
          echo "RELEASE_TAG=${{ github.event.inputs.override-tag }}" >> $GITHUB_ENV

      # make the release
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          commit: ${{ needs.fetch-run.outputs.publish-commit }}
          name: ${{ env.RELEASE_TAG }}
          body: |
            # BiobankingUK Directory ${{ env.RELEASE_TAG }}

            ## Assets available for download:

            - BiobankingUK Directory application
              - for the .NET Runtime (cross platform)
            - PostgreSQL migrations bundle
              - for Windows (x64)
              - for Linux (x64)
          generateReleaseNotes: true
          prerelease: ${{ steps.version.outputs.pre-release != '' || github.events.inputs.override-tag != '' }}
          makeLatest: ${{ env.is-latest }}
          updateOnlyUnreleased: true
          allowUpdates: true
          removeArtifacts: true # remove existing artifacts when updating
          artifacts: directory*.zip,migrations*.zip
          artifactContentType: application/zip
